### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by cameron314** [cameron314/PNGEncoder2#3]
When encoding many images, the memory usage of Flash Player steadily increases and never declines.

I tried picking some low-hanging fruit (objects that were being created every frame), but it seems there's still a leak, particularly of Vector<*>, somehow (investigation of the code the HaXe compiler produces is probably in order).

This issue was brought to my attention by Kamel on my blog -- thanks for the debugging help!

Screenshot of profile (courtesy of Kamel): 
![PNGEnocder2 memory leak](https://f.cloud.github.com/assets/116235/290582/75ecc26c-92e8-11e2-88db-be2e6f006dcf.png)

**Comment by francisvidal** [comment]
Hi.  On mobile there is a 24889 bytes in use in a BytesArray even after I clean everything.  It seems to be in the static variable data.   I don't think it's leaking, but I need every memory for my app, not for a one time operation.  Can you .clear(); the data variable after the COMPLETE event?  Or add a destroy method that we can call to do it?

Thanks.

**Comment by sa6k0o0** [comment]
Well, I don't have the code with me right now, I have it on my desktop in
Bulgaria. And now I am in Los Angeles , California.

But it is possible that the runtime from adobe at the time might have been
buggy and might have created that memory issue.
I actually switched away from flash and now I make video games with Unity.
Flash had too many bugs.

Thanks
Aleks

**Comment by cameron314** [comment]
@francisvidal: I'll have to look at the code, but I do recall having some reusable memory hanging around (particularly a CRC-32 table that's generated just the first time, if I'm not mistaken). I'll add a method to clear all cached data for resource-constrained users.

@sa6k0o0: Yep, too many bugs indeed!

**Comment by francisvidal** [comment]
@cameron314 & @sa6k0o0  Thank you both for your fast answer. 

In the debugger I can see that this var: (private static var data : ByteArray;// The select()ed working memory) still hold some memory after the encoding.  I don't know about the CRC-32 table.  In Scout I also see some byteArray that is never released.

I have done some test with Haxe some years ago, but to setup myself and understand the code would really take my quite some time.  So if anyone of you can take a look and solve this issue I would be very grateful.

BTW the speed of this library is amazing!

**Comment by cameron314** [comment]
@francisvidal: I've pushed a commit to the master which adds a `freeCachedMemory()` method. You can call it after encoding an image to let go all the temporary memory that is normally hogged to make the next encoding faster. Depending on how you encode your images, and their size, this may save several kilobytes or even megabytes of memory :-)

**Comment by francisvidal** [comment]
Thank you so much!

**Comment by cameron314** [comment]
@francisvidal: I've [published a new release](https://github.com/cameron314/PNGEncoder2/releases/tag/v1.4) which contains this feature. Cheers :-)
