### ISSUE TITLE
Error #1000: The system is out of memory

### ISSUE THREAD

**Issue by damoebius** [cameron314/PNGEncoder2#5]
Hi,
I've got an Exception while encoding a huge picture, 6201x6201px in a Air 3.4 application.

at flash.utils::ByteArray/set length()
	at _PNGEncoder2::PNGEncoder2Impl$/writeIDATChunk()
	at PNGEncoder2$/encode()
Before encoding call, Scout tell me that i used only 200MB of memory and After exception, system memory manager tell me that adl.exe used 1.5GB.

Is there a way to optimize memory usage of your encoder ?
Is it possible to encode partial part of the picture but save a full PNG with FileStream for exemple ?

**Comment by cameron314** [comment]
For anybody else looking at this issue, there's also the new `freeCachedMemory` method which you can call after an image has finished being encoded. It will release all temporary memory that was used during the encoding process.
